### ISSUE TITLE
Favourites overlapping each other

### ISSUE THREAD

**Issue by bintheir** [bxpluse/twitch-pin-favorites#6]
A new Twitch tab will load just fine, but after a while, favourites are overlapping each other.
I've seen it happening after I switch back to the Twitch browser tabs, but also when Twitch is in the foreground long enough.

My best guess is that it happens when the 'Followed Channels' list is automatically updated/refreshed.

![image](https://github.com/bxpluse/twitch-pin-favorites/assets/85111690/8aeda133-0a3d-40f7-b531-fbf463f35d16)

Windows 10 pro
Add-on 1.8.2
Firefox 123.1 and 124

**Comment by bintheir** [comment]
I don't know if 1.8.3 was released to fix this issue, but I still have the same overlapping issue.

Windows 10 pro
Add-on 1.8.3
Firefox 124.0.1

**Comment by bintheir** [comment]
@bxpluse After the latest browser update, the overlapping issue still exists.

Windows 10 pro
Add-on 1.8.3
Firefox 124.0.2

**Comment by Beracosa** [comment]
1.8.3 of the add-on was to address the nav bar not expanding.

I'm on the same versions of the browser and add-on, but have only encountered this issue once so assumed it was a one-off. Even leaving the tab there for hours I'm not able to reproduce the issue again 🤔.

**Comment by bintheir** [comment]
I have it often, like really often.
Do you have any other add-ons for Twitch enabled?
I have BetterTTV and FrankerFaceZ, maybe it's conflicting with that. For example, I've set the option to have chat on the left side and Following List on the right side.

I'll disable the sidebar switch and see how it goes.
If it doesn't improve, I'll try disabling one or both BetterTTV/FrankerFaceZ.

**Comment by bintheir** [comment]
@bxpluse I've had tried changing some settings, or disabling a single add-on, but the issue remained.
Eventually disabled all add-ons that could influence Twitch, but still, the issue remains.

**Comment by Beracosa** [comment]
Just spitballing, could from be Twitch A/B testing before rolling out a new feature or hardware differences.

I'll take another crack at this rendering issue when I have time in a couple weeks. Feel free to check out the code locally if you'd like to try making a fix too.

**Comment by bintheir** [comment]
I'd like to, but I can't program and barely read code.
I can read your comments in the code though, and if I understand correctly, it seems that it tries to detect change, and it runs an update when changes occur.

Maybe, when it detects a change, that it can run the initial load instead of an update? The initial load always seems to run fine and makes the process less complex.


Edit:
Maybe it has to do with Twitch implementing this new sponsor type into the sidebar, this is forcefully pushed to the top disregarding sorting type.
![image](https://github.com/bxpluse/twitch-pin-favorites/assets/85111690/2253324d-2c4f-4718-b530-6f59cf57fb8b)

**Comment by Beracosa** [comment]
Good find on the sponsor type! I use an adblock and never noticed it.

I attempted a fix for this. Please update the add-on to version 1.8.4, and let me know if you still encounter this issue.

**Comment by bintheir** [comment]
Updated as soon as 1.8.4 was available, and the list has been displayed correctly even since.
The issue seems to be resolved!
